### ISSUE TITLE
Modelo 3D de J1 y D3

### ISSUE THREAD

**Issue by brengi** [CastroGerman/Themu-Hardware#6]
Cambiar  la ruta C:/Users/germi/Downloads/User Library-MicroUSB-B_Molex_105017-0001/User Library-MicroUSB-B_Molex_105017-0001.STEP
por:
${KIPRJMOD}/3DShapes/User Library-MicroUSB-B_Molex_105017-0001.wrl 
Lo mismo para:
${KIPRJMOD}/3DShapes/User Library-LED_0605.wrl
Aunque recomiendo un led más grande así no se la complican al armar. Algún 0805. Noten que 0605 es el tamaño del cuerpo pero los pads son incluso más chicos que un 0603.

**Comment by CastroGerman** [comment]
Creemos poder soldar D3, aun así la zona donde se ubica no es critica y podría reemplazarse sin muchos inconvenientes por un 0805. Será tenido en cuenta para el próximo commit junto con las modificaciones de las rutas de los modelos 3D.

**Comment by CastroGerman** [comment]
Finalmente D3 fue reemplazado por [QBLP655R-RGB](https://static6.arrow.com/aropdfconversion/2e9f9b5de02200d8efd894b12d78141ca956a5cd/qblp655-rgb.pdf) en 1205.
