### ISSUE TITLE
Margen general 0,2mm muy chico 

### ISSUE THREAD

**Issue by brengi** [CastroGerman/Themu-Hardware#7]
Con el ancho de pista actual el PCB permite un margen de 0,25mm, agregando una excepción de margen para U1 (márgen local de 0,2mm). 
Otra forma de verlo es que las pistas de 0,152 son muy finas y delicadas. Recomiendo subir a 0,25 donde se pueda, o por lo menos ceca de J1. El USB es lo primero que se estropea y necesita retrabajo en un celular.
NOTA: Se debe elegir entre subir el margen o subir la pista (hacer ambas cosas se complica sin agrandar el PCB). O simplemente no hacer ninguna de las dos y mantener el nivel de riesgo actual.

**Comment by CastroGerman** [comment]
El ancho de pistas en las cercanías de J1 puede agrandarse a 0.25 mm (10 mils) sin mayores inconvenientes, por lo que el próximo commit contendrá este cambio!
Adicionalmente, estamos evaluando aplicar el mismo criterio para las líneas de alimentación principales (VBUS, BATT, entrada y salida del regulador lineal).
