### ISSUE TITLE
Leyenda Industria Argentina

### ISSUE THREAD

**Issue by brengi** [CastroGerman/Themu-Hardware#8]
Consultar con el fabricante de Rosario si la fabrican ellos o la mandan afuera. He escuchado casos donde por tener la leyenda de IND. ARG. en aduana genera inconvenientes. En esos caso conviene Diseño Argentino. Si la placa realmente se fabrica acá no hay problema.

**Comment by CastroGerman** [comment]
De todas formas la leyenda fue cambiada.
